version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    restart: always
    volumes:
      - ./:/var/www/symfony:delegated
      - /var/www/symfony/vendor
      - /var/www/symfony/var
      - ./docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom-php.ini:ro
    networks:
      - symfony

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/symfony:delegated
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony

  mysql:
    image: mysql:8.0
    container_name: symfony_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - symfony

networks:
  symfony:
    driver: bridge
    name: symfony

volumes:
  mysql_data:
